### ISSUE TITLE
小白学习CNN的问题

### ISSUE THREAD

**Issue by WHITEGHOSTS** [ahmedfgad/NumPyCNN#9]
就是在第二层和第三层的卷积核为什么要用随机数赋值，不是很懂这些原理

**Comment by ahmedfgad** [comment]
At first I used Google for translating your comment into English.
Usually, all kernels of CNN are randomly initialized. These kernels are actually the weights that the CNN learns. In this project, I initialized the first 2 kernels to calculate the horizontal and vertical gradients. The reason is that this project is part of one of my books and I was taking screenshots from the result of each layer. When I used these 2 kernels, the result was easily interpreted by the reader compared to starting with randomly initialized kernels.
Away from confusion, usually all kernels in CNN are randomly initialized.
